defaults: &defaults

:development:
  :postgresql:
    :username: username
    :password: password
    :database: database
    :host: localhost
    :port: 5432

:test:
  :postgresql:
    :username: username
    :password: password
    :database: database
    :host: localhost
    :port: 5432

:production:
  :postgresql:
    :username: username
    :password: password
    :database: database
    :host: localhost
    :port: 5432